// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcjO61aj3AIe-bLAmt2Vn_5bupYtJ5eXM',
    appId: '1:1084004849478:web:0d11d039e73e57fac63747',
    messagingSenderId: '1084004849478',
    projectId: 'bio-odonto',
    authDomain: 'bio-odonto.firebaseapp.com',
    storageBucket: 'bio-odonto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCayjQCFAYxvegv4MjXV3zD4sayXQZ8fuA',
    appId: '1:1084004849478:android:98c37a1b10ac3067c63747',
    messagingSenderId: '1084004849478',
    projectId: 'bio-odonto',
    storageBucket: 'bio-odonto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZ_zipHdwOXddie5QoCYcr3quGJ7DAwk',
    appId: '1:1084004849478:ios:e6936279a7389153c63747',
    messagingSenderId: '1084004849478',
    projectId: 'bio-odonto',
    storageBucket: 'bio-odonto.firebasestorage.app',
    iosClientId: '1084004849478-k5lapme64dsl003dbltjd5n8ifdj2htf.apps.googleusercontent.com',
    iosBundleId: 'com.bioodonto.bioodonto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcjO61aj3AIe-bLAmt2Vn_5bupYtJ5eXM',
    appId: '1:1084004849478:web:7223798bee1928f0c63747',
    messagingSenderId: '1084004849478',
    projectId: 'bio-odonto',
    authDomain: 'bio-odonto.firebaseapp.com',
    storageBucket: 'bio-odonto.firebasestorage.app',
  );
}